version: '3.8'
services:
  projekt-pekao:
    build:
      context: .
      target: development
    ports:
      - "8000:8000"
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
      - MYSQL_URL=jdbc:mysql://mysqlserver/library
    volumes:
      - ./:/app
    depends_on:
      - mysqlserver
    profiles:
      - dev

  mysqlserver:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=tomek
      - MYSQL_PASSWORD=coderslab
      - MYSQL_DATABASE=library
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
volumes:
  mysql_data:
  mysql_config:
